import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/web-api/linkiir-api",
    },
    {
      type: "category",
      label: "Projects",
      items: [
        {
          type: "doc",
          id: "api/web-api/get-projects-api-get-projects-get",
          label: "List all projects",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/create-project-api-create-project-post",
          label: "Create a project",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/get-project-collaborators-api-project-collaborators-guid-get",
          label: "List a project's collaborators",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/add-project-collaborators-api-project-collaborators-guid-post",
          label: "Add collaborators to a project",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/remove-project-collaborator-api-project-collaborators-guid-name-delete",
          label: "Remove a collaborator from a project",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/web-api/delete-project-api-delete-project-guid-delete",
          label: "Delete a project",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/web-api/export-project-api-export-project-guid-get",
          label: "Export a project as a .zip bundle",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/import-project-zip-api-import-project-zip-post",
          label: "Import a project from a zip bundle",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/import-project-remote-api-import-project-remote-post",
          label: "Import a project by cloning its git remote",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/reorder-projects-api-reorder-projects-post",
          label: "Reorder projects",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/update-project-api-update-project-guid-put",
          label: "Rename or update a project",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/web-api/update-project-variables-api-update-project-variables-guid-put",
          label: "Update project variables",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/web-api/update-project-git-config-api-update-project-git-config-guid-put",
          label: "Update project git remote",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/web-api/push-project-git-api-push-project-git-guid-post",
          label: "Push a project's git state to its cloud remote",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/pull-project-git-api-pull-project-git-guid-post",
          label: "Pull a project's dev clone from its git remote",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/abort-project-merge-git-api-abort-project-merge-git-guid-post",
          label: "Abort an in-progress project merge",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/get-project-git-status-api-get-project-git-status-guid-get",
          label: "Get project git status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/get-project-git-log-api-get-project-git-log-guid-get",
          label: "Get project git log",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/get-workflow-node-commits-api-get-workflow-node-commits-guid-get",
          label: "Get every node's newest commit for one workflow",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/get-project-git-commit-files-api-get-project-git-commit-files-guid-get",
          label: "List files changed in a git commit",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/get-project-git-file-diff-api-get-project-git-file-diff-guid-get",
          label: "Get a single file's before/after content for a git commit",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/get-project-git-working-file-diff-api-get-project-git-working-file-diff-guid-get",
          label: "Get a file's working-tree git diff",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/restore-project-git-file-api-restore-project-git-file-guid-post",
          label: "Restore a file to a prior commit",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/restore-project-git-commit-api-restore-project-git-commit-guid-post",
          label: "Restore selected files to a prior commit",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/commit-project-git-api-commit-project-git-guid-post",
          label: "Commit staged changes in a project's dev clone",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/stage-project-git-path-api-stage-project-git-path-guid-post",
          label: "Stage a single path in a project's dev clone",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/unstage-project-git-path-api-unstage-project-git-path-guid-post",
          label: "Unstage a single path in a project's dev clone",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/stage-all-project-git-api-stage-all-project-git-guid-post",
          label: "Stage all changes in a project's dev clone",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/unstage-all-project-git-api-unstage-all-project-git-guid-post",
          label: "Unstage all changes in a project's dev clone",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/start-project-api-start-project-post",
          label: "Start every workflow in a project",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/stop-project-api-stop-project-post",
          label: "Stop a project",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/reload-project-api-reload-project-post",
          label: "Reload a project in the runtime",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/get-project-status-api-project-status-get",
          label: "Get project runtime status",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Libraries",
      items: [
        {
          type: "doc",
          id: "api/web-api/get-project-libraries-api-get-project-libraries-get",
          label: "List a project's libraries",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/create-library-api-create-library-post",
          label: "Create a project library",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/get-library-dependents-api-get-library-dependents-get",
          label: "List nodes that depend on a library",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/delete-library-api-delete-library-post",
          label: "Delete a project library",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/import-libraries-api-import-libraries-post",
          label: "Import libraries from another project",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/publish-library-version-api-publish-library-version-post",
          label: "Publish a library version",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/get-library-tree-api-get-library-tree-get",
          label: "Get a library's file tree",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/get-library-files-api-get-library-files-get",
          label: "Get a library's working-copy files",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/get-library-version-files-api-get-library-version-files-get",
          label: "Get a published library version's files",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/create-library-file-api-create-library-file-post",
          label: "Create an empty file in a library",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/create-library-folder-api-create-library-folder-post",
          label: "Create a folder in a library",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/save-library-file-api-save-library-file-post",
          label: "Save a library file's content",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/rename-library-entry-api-rename-library-entry-post",
          label: "Rename a file or folder in a library",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/move-library-entry-api-move-library-entry-post",
          label: "Move a file or folder within a library",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/delete-library-entry-api-delete-library-entry-post",
          label: "Delete a file or folder from a library",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/add-library-dep-api-add-library-dep-post",
          label: "Link a node to a project library",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/remove-library-dep-api-remove-library-dep-post",
          label: "Unlink a node from a project library",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/convert-node-entry-to-library-api-convert-node-entry-to-library-post",
          label: "Convert a node file/folder into a project library",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Catalogs",
      items: [
        {
          type: "doc",
          id: "api/web-api/install-catalog-library-api-install-catalog-library-post",
          label: "Install a catalog's library into a project",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/catalog-library-dependents-api-catalog-library-dependents-get",
          label: "List nodes across the grid using a catalog's library",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/project-library-dependents-api-project-library-dependents-get",
          label: "List a project's nodes using one of its own libraries",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/update-library-dependents-api-update-library-dependents-post",
          label: "Move chosen nodes onto a newer version of a catalog's library",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/catalog-node-dependents-api-catalog-node-dependents-get",
          label: "List nodes across the grid whose catalog adapter has a newer release",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/update-nodes-from-template-api-update-nodes-from-template-post",
          label: "Move chosen nodes onto a newer release of their catalog adapter",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/subscribe-catalog-api-subscribe-catalog-post",
          label: "Subscribe to a published catalog",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/get-catalogs-api-get-catalogs-get",
          label: "List catalogs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/catalog-sync-status-api-catalog-sync-status-get",
          label: "What each catalog has waiting, from the last check",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/refresh-catalog-sync-api-refresh-catalog-sync-post",
          label: "Check every catalog for waiting updates now",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/pull-catalog-api-pull-catalog-local-name-post",
          label: "Update a catalog from its repository",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/update-catalog-api-catalog-local-name-put",
          label: "Change which ref a catalog tracks, or the key it authenticates with",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/web-api/delete-catalog-api-catalog-local-name-delete",
          label: "Remove a catalog",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/web-api/browse-catalog-api-browse-catalog-local-name-get",
          label: "List a catalog's node templates and libraries",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/catalog-updates-api-catalog-updates-local-name-get",
          label: "Preview what updating a catalog would change",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/create-catalog-api-create-catalog-post",
          label: "Create a catalog to publish from this grid",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/publish-catalog-api-publish-catalog-local-name-post",
          label: "Publish a catalog to its repository",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/add-catalog-node-template-api-add-catalog-node-template-post",
          label: "Add a project's node template to a catalog",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/add-catalog-node-api-add-catalog-node-post",
          label: "Add a node straight from a workflow to a catalog",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/add-catalog-library-api-add-catalog-library-post",
          label: "Add a project's published library version to a catalog",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/remove-catalog-node-template-api-catalog-node-template-local-name-slug-delete",
          label: "Remove a node template from a catalog",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/web-api/remove-catalog-library-api-catalog-library-local-name-name-delete",
          label: "Remove a library, or one of its versions, from a catalog",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/web-api/set-catalog-write-access-api-catalog-write-access-local-name-put",
          label: "Confirm or give up write access to a catalog",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/web-api/export-catalog-api-export-catalog-local-name-post",
          label: "Write a catalog into a folder on this server",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Nodes",
      items: [
        {
          type: "doc",
          id: "api/web-api/start-node-api-start-node-post",
          label: "Start a node",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/stop-node-api-stop-node-post",
          label: "Stop a node",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/restart-node-api-restart-node-post",
          label: "Restart a node",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/get-node-status-api-node-status-get",
          label: "Get a single node's status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/list-nodes-api-list-nodes-get",
          label: "List running nodes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/create-node-api-create-node-project-guid-workflow-guid-post",
          label: "Create a node",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/get-node-templates-api-get-node-templates-get",
          label: "List node templates",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/get-node-locked-fields-api-node-locked-fields-get",
          label: "Get locked field definitions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/update-node-config-api-update-node-config-project-guid-workflow-guid-node-guid-put",
          label: "Update a node's config fields",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/web-api/update-node-details-api-update-node-details-project-guid-workflow-guid-node-guid-put",
          label: "Update a node's name, type, and description",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/web-api/set-node-run-commit-api-set-node-run-commit-project-guid-workflow-guid-node-guid-put",
          label: "Pin a node to a commit",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/web-api/node-template-status-api-node-template-status-project-guid-get",
          label: "List a project's catalog-backed nodes and their update state",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/node-template-versions-api-node-template-versions-project-guid-workflow-guid-node-guid-get",
          label: "List the versions of a node's catalog adapter",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/update-node-from-template-api-update-node-from-template-project-guid-workflow-guid-node-guid-post",
          label: "Update a node to its catalog's current version",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/unlink-node-template-api-unlink-node-template-project-guid-workflow-guid-node-guid-post",
          label: "Stop a node following its catalog",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/create-node-template-api-create-node-template-project-guid-workflow-guid-node-guid-post",
          label: "Create a node template from an existing node",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/get-node-template-api-get-node-template-project-guid-node-type-slug-get",
          label: "Get a node template",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/update-node-template-api-update-node-template-project-guid-node-type-slug-put",
          label: "Update a node template",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/web-api/delete-node-template-api-delete-node-template-project-guid-node-type-slug-delete",
          label: "Delete a node template",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/web-api/import-node-templates-api-import-node-templates-post",
          label: "Import node templates from another project",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/delete-node-api-delete-node-project-guid-workflow-guid-node-guid-delete",
          label: "Delete a node",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/web-api/create-connection-api-create-connection-project-guid-workflow-guid-post",
          label: "Create a connection between two nodes",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/delete-connection-api-delete-connection-project-guid-workflow-guid-source-guid-target-guid-delete",
          label: "Delete a connection between two nodes",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/web-api/get-node-api-get-node-get",
          label: "Get a node's configuration",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/get-node-files-api-get-node-files-get",
          label: "List a node's files",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/create-node-file-api-create-node-file-post",
          label: "Create a node file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/create-node-folder-api-create-node-folder-post",
          label: "Create a node folder",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/rename-node-entry-api-rename-node-entry-post",
          label: "Rename a node file or folder",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/delete-node-entry-api-delete-node-entry-post",
          label: "Delete a node file or folder",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/move-node-entry-api-move-node-entry-post",
          label: "Move a node file or folder",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/save-node-file-api-save-node-file-post",
          label: "Save a node file's contents",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/get-node-samples-api-get-node-samples-get",
          label: "List a node's test samples",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/create-node-sample-api-create-node-sample-post",
          label: "Create a test sample for a node",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/update-node-sample-api-update-node-sample-post",
          label: "Update a node's test sample",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/delete-node-sample-api-delete-node-sample-post",
          label: "Delete a node's test sample",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/run-node-test-api-run-node-test-post",
          label: "Run a node's script against a sample",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/get-node-schema-api-get-node-schema-get",
          label: "Get a node's parsed grammar schemas",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/start-debug-api-debug-start-post",
          label: "Start a Lua debug session",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/control-debug-api-debug-control-post",
          label: "Control an active Lua debug session",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Workflows",
      items: [
        {
          type: "doc",
          id: "api/web-api/start-workflow-api-start-workflow-post",
          label: "Start a workflow",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/stop-workflow-api-stop-workflow-post",
          label: "Stop a workflow",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/restart-workflow-api-restart-workflow-post",
          label: "Restart a workflow",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/get-workflow-status-api-workflow-status-get",
          label: "Get a workflow's live status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/get-workflows-api-get-workflows-get",
          label: "List a project's workflows",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/create-workflow-api-create-workflow-project-guid-post",
          label: "Create a workflow",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/delete-workflow-api-delete-workflow-project-guid-workflow-guid-delete",
          label: "Delete a workflow",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/web-api/update-workflow-api-update-workflow-project-guid-workflow-guid-put",
          label: "Update a workflow",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/web-api/save-node-positions-api-save-node-positions-workflow-guid-put",
          label: "Save node canvas positions for a workflow",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Monitor",
      items: [
        {
          type: "doc",
          id: "api/web-api/stream-events-api-stream-events-get",
          label: "Stream runtime events (SSE)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/get-project-list-api-project-list-get",
          label: "List projects for the monitor page",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/get-workflow-list-api-workflow-list-get",
          label: "List workflows for the monitor page",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/get-workflow-activity-api-workflow-activity-get",
          label: "Last activity and unacknowledged error counts per workflow",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/clear-errors-api-clear-errors-post",
          label: "Mark a workflow's or node's current errors as seen",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Templates",
      items: [
        {
          type: "doc",
          id: "api/web-api/create-template-group-api-create-template-group-post",
          label: "Create a template group",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/get-template-group-git-config-api-get-template-group-git-config-name-get",
          label: "Get a template group's git config",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/update-template-group-git-config-api-update-template-group-git-config-name-put",
          label: "Update a template group's git config",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/web-api/push-template-group-git-api-push-template-group-git-name-post",
          label: "Push a template group's git repository",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Settings",
      items: [
        {
          type: "doc",
          id: "api/web-api/get-env-data-api-env-data-get",
          label: "Get environment variable data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/update-env-data-api-env-data-put",
          label: "Update environment variable data",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/web-api/get-database-settings-api-database-settings-get",
          label: "Get database connection settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/update-database-settings-api-database-settings-put",
          label: "Update database connection settings",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/web-api/get-server-settings-api-server-settings-get",
          label: "Get server settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/update-server-settings-api-server-settings-put",
          label: "Update server settings",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/web-api/restart-grid-api-restart-grid-post",
          label: "Restart the Grid process",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/restart-runtime-route-api-restart-runtime-post",
          label: "Restart the Runtime process",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/get-backup-settings-route-api-backup-settings-get",
          label: "Get instance backup settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/update-backup-settings-api-backup-settings-put",
          label: "Update instance backup settings",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/web-api/run-instance-backup-api-run-instance-backup-post",
          label: "Run an instance backup now",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/restore-instance-route-api-restore-instance-post",
          label: "Restore this instance from a remote",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/get-instance-git-log-api-instance-git-log-get",
          label: "Get the instance's git commit history",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/get-instance-git-commit-files-api-instance-git-commit-files-get",
          label: "List files changed in an instance git commit",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/get-instance-git-file-diff-api-instance-git-file-diff-get",
          label: "Get a single file's before/after content for an instance git commit",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/get-security-settings-route-api-security-settings-get",
          label: "Get session security settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/update-security-settings-api-security-settings-put",
          label: "Update session security settings",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/web-api/get-http-server-settings-api-http-server-settings-get",
          label: "Get HTTP server settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/update-http-server-settings-api-http-server-settings-put",
          label: "Update HTTP server settings",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/web-api/get-permission-catalog-api-permission-catalog-get",
          label: "List every assignable permission",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/get-role-settings-api-role-settings-get",
          label: "List roles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/create-role-api-create-role-post",
          label: "Create a role",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/update-role-api-update-role-name-put",
          label: "Update a role's permissions",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/web-api/delete-role-api-delete-role-name-delete",
          label: "Delete a role",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/web-api/get-user-settings-api-user-settings-get",
          label: "List users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/create-user-api-create-user-post",
          label: "Create a user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/update-user-api-update-user-name-put",
          label: "Update a user",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/web-api/delete-user-api-delete-user-name-delete",
          label: "Delete a user",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/web-api/get-version-info-api-version-info-get",
          label: "Get version and directory info",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Kafka",
      items: [
        {
          type: "doc",
          id: "api/web-api/queue-counts-api-queue-counts-get",
          label: "Get queue depth per workflow and node",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/message-rates-api-dashboard-message-rates-get",
          label: "Get current message in/out rates",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/message-rate-history-api-dashboard-message-rate-history-get",
          label: "Get 24-hour message rate history",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/clear-queue-api-clear-queue-post",
          label: "Clear a node's or workflow's queue",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/node-queue-api-node-queue-get",
          label: "Read a node's queue",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/reposition-queue-api-reposition-queue-post",
          label: "Move a node's position in its queue",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Dashboard",
      items: [
        {
          type: "doc",
          id: "api/web-api/get-cpu-usage-api-dashboard-cpu-usage-get",
          label: "Get current CPU usage",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/get-memory-usage-api-dashboard-memory-usage-get",
          label: "Get current memory usage",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/grid-status-api-dashboard-grid-status-get",
          label: "Get grid uptime status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/status-api-status-get",
          label: "Status",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Health",
      items: [
        {
          type: "doc",
          id: "api/web-api/health-api-health-get",
          label: "Health",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/get-items-api-items-get",
          label: "Get Items",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Files",
      items: [
        {
          type: "doc",
          id: "api/web-api/browse-path-api-browse-path-get",
          label: "Browse a server-side directory",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Auth",
      items: [
        {
          type: "doc",
          id: "api/web-api/login-api-login-post",
          label: "Log in",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/logout-api-logout-post",
          label: "Log out",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/current-user-api-current-user-get",
          label: "Get the current user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/change-password-api-change-password-post",
          label: "Change the current user's password",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Archiver Fleet",
      items: [
        {
          type: "doc",
          id: "api/web-api/get-archiver-config-api-archivers-config-get",
          label: "Get archiver fleet configuration",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/list-archivers-api-archivers-get",
          label: "List archiver instances",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/create-archiver-api-archivers-post",
          label: "Create an archiver instance",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/get-archiver-api-archivers-instance-id-get",
          label: "Get an archiver instance",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/remove-archiver-api-archivers-instance-id-delete",
          label: "Remove an archiver instance",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/web-api/start-archiver-api-archivers-instance-id-start-post",
          label: "Start an archiver instance",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/stop-archiver-api-archivers-instance-id-stop-post",
          label: "Stop an archiver instance",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/set-archiver-auto-restart-api-archivers-instance-id-auto-restart-post",
          label: "Toggle auto-restart for an archiver instance",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Logs",
      items: [
        {
          type: "doc",
          id: "api/web-api/get-logs-api-logs-get",
          label: "Query logs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/get-logs-related-api-logs-related-get",
          label: "Get related log records",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/get-logs-facets-api-logs-facets-get",
          label: "Get log filter facets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/get-log-index-status-api-logs-index-status-get",
          label: "Log index build status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/get-log-payload-api-logs-event-id-payload-get",
          label: "Get a log record's stored payload",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/post-logs-resubmit-api-logs-resubmit-post",
          label: "Resubmit log events to Kafka",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/export-logs-api-logs-export-post",
          label: "Export selected log records as a downloadable file",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Log Settings",
      items: [
        {
          type: "doc",
          id: "api/web-api/get-log-settings-api-settings-logs-get",
          label: "Get log archiver settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/update-log-settings-api-settings-logs-put",
          label: "Update log archiver settings",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/web-api/restart-all-archivers-api-settings-logs-restart-all-post",
          label: "Restart all archiver instances",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/test-connection-api-settings-logs-test-connection-post",
          label: "Test log database connectivity",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "License",
      items: [
        {
          type: "doc",
          id: "api/web-api/get-license-api-license-get",
          label: "Get the current license status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/install-license-api-license-post",
          label: "Install a license code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/delete-license-api-license-delete",
          label: "Remove the installed license",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/web-api/get-fingerprint-api-license-fingerprint-get",
          label: "Get the installation's license fingerprint",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/release-license-api-license-release-post",
          label: "Declare a license migration",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Notification Settings",
      items: [
        {
          type: "doc",
          id: "api/web-api/get-notification-settings-api-settings-notifications-get",
          label: "Get notification settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/update-notification-settings-api-settings-notifications-put",
          label: "Update notification settings",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/web-api/test-email-api-settings-notifications-test-email-post",
          label: "Send a test email",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/test-alert-node-api-settings-notifications-test-alert-node-post",
          label: "Send a test alert to the Alert Node",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/get-notification-engine-health-api-notification-engine-health-get",
          label: "Get notification engine health and consumer lag",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Notification Rules",
      items: [
        {
          type: "doc",
          id: "api/web-api/get-notification-rules-api-notification-rules-get",
          label: "List all notification rules",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/web-api/create-notification-rule-api-notification-rules-post",
          label: "Create a notification rule",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/web-api/update-notification-rule-api-notification-rules-rule-id-put",
          label: "Update a notification rule",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/web-api/delete-notification-rule-api-notification-rules-rule-id-delete",
          label: "Delete a notification rule",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/web-api/re-enable-notification-rule-api-notification-rules-rule-id-re-enable-post",
          label: "Re-enable a rule the engine auto-disabled after a fault",
          className: "api-method post",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
